# Generated by Django 6.0.1 on 2026-01-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credyjobboard', '0002_job_image_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary'), ('remote', 'Remote'), ('other', 'Other')], default='full_time', max_length=32),
        ),
    ]
