# Generated by Django 6.0.1 on 2026-01-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credyjobboard', '0007_crawlerdashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrawlerDashboard',
        ),
    ]
