# Generated by Django 6.0.1 on 2026-01-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credyjobboard', '0008_delete_crawlerdashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Crawler Dashboard',
                'verbose_name_plural': 'Crawler Dashboard',
            },
        ),
    ]
