# Generated by Django 6.0.1 on 2026-01-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credyjobboard', '0010_crawledjob_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlsource',
            name='cron_expression',
            field=models.CharField(blank=True, help_text='If custom, use standard cron format.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='frequency',
            field=models.CharField(choices=[('manual', 'Manual Only'), ('5min', 'Every 5 Minutes'), ('10min', 'Every 10 Minutes'), ('30min', 'Every 30 Minutes'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom Cron Expression')], default='manual', max_length=32),
        ),
        migrations.AddField(
            model_name='crawlsource',
            name='next_run',
            field=models.DateTimeField(blank=True, help_text='Next scheduled run time (auto-managed)', null=True),
        ),
    ]
