# Generated by Django 6.0.1 on 2026-01-25 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credyjobboard', '0011_crawlsource_cron_expression_crawlsource_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('jobs_found', models.IntegerField(default=0)),
                ('jobs_updated', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credyjobboard.crawlsource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
